name: DarkDev Builder
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build DarkDev
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          export THEOS=~/theos
          make package
      - uses: actions/upload-artifact@v4
        with:
          name: DarkDev-Dylib
          path: packages/*.deb
