name: DarkDev Builder
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $THEOS
          mkdir -p $THEOS/sdks
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz -o $THEOS/sdks/sdk.tar.xz
          tar -xf $THEOS/sdks/sdk.tar.xz -C $THEOS/sdks/
          rm $THEOS/sdks/sdk.tar.xz

      - name: Build DarkDev
        run: |
          make package
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DarkDev-Dylib
          path: packages/*.deb
