name: Build DarkDev Client
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Κατέβασμα του Theos απευθείας
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
          # Κατέβασμα των SDKs χειροκίνητα για να μην χτυπάει το API Error
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          
          # Ρύθμιση της διαδρομής
          echo "THEOS=~/theos" >> $GITHUB_ENV
          
      - name: Build DarkDev
        run: |
          export THEOS=~/theos
          # Φτιάχνουμε το πακέτο
          make package
          
      - name: Upload DarkDev Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DarkDev-Dylib
          path: packages/*.deb
